//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinaUnaXamarin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KinaUnaXamarin.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Info.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Level.
        /// </summary>
        internal static string AccessLevel {
            get {
                return ResourceManager.GetString("AccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Child.
        /// </summary>
        internal static string AddChild {
            get {
                return ResourceManager.GetString("AddChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        internal static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contact.
        /// </summary>
        internal static string AddContact {
            get {
                return ResourceManager.GetString("AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contact for:.
        /// </summary>
        internal static string AddContactFor {
            get {
                return ResourceManager.GetString("AddContactFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Friend.
        /// </summary>
        internal static string AddFriend {
            get {
                return ResourceManager.GetString("AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Friend for:.
        /// </summary>
        internal static string AddFriendFor {
            get {
                return ResourceManager.GetString("AddFriendFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        internal static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Measurement.
        /// </summary>
        internal static string AddMeasurement {
            get {
                return ResourceManager.GetString("AddMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Measurement for:.
        /// </summary>
        internal static string AddMeasurementFor {
            get {
                return ResourceManager.GetString("AddMeasurementFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photo.
        /// </summary>
        internal static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photo for:.
        /// </summary>
        internal static string AddPhotoFor {
            get {
                return ResourceManager.GetString("AddPhotoFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        internal static string AddressLine1 {
            get {
                return ResourceManager.GetString("AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        internal static string AddressLine2 {
            get {
                return ResourceManager.GetString("AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Skill.
        /// </summary>
        internal static string AddSkill {
            get {
                return ResourceManager.GetString("AddSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Skill for:.
        /// </summary>
        internal static string AddSkillFor {
            get {
                return ResourceManager.GetString("AddSkillFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sleep.
        /// </summary>
        internal static string AddSleep {
            get {
                return ResourceManager.GetString("AddSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sleep for:.
        /// </summary>
        internal static string AddSleepFor {
            get {
                return ResourceManager.GetString("AddSleepFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User for:.
        /// </summary>
        internal static string AddUserFor {
            get {
                return ResourceManager.GetString("AddUserFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrators.
        /// </summary>
        internal static string Administrators {
            get {
                return ResourceManager.GetString("Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average sleep per day:.
        /// </summary>
        internal static string AverageSleepPerDay {
            get {
                return ResourceManager.GetString("AverageSleepPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average sleep per day in the last 30 days:.
        /// </summary>
        internal static string AverageSleepPerDayInTheLast30Days {
            get {
                return ResourceManager.GetString("AverageSleepPerDayInTheLast30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average sleep per day in the last year:.
        /// </summary>
        internal static string AverageSleepPerDayInTheLastYear {
            get {
                return ResourceManager.GetString("AverageSleepPerDayInTheLastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caretakers.
        /// </summary>
        internal static string CaretakerFriends {
            get {
                return ResourceManager.GetString("CaretakerFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: When changing language, some text may appear in the previously selected language until the app is restarted..
        /// </summary>
        internal static string ChangeLanguageWarning {
            get {
                return ResourceManager.GetString("ChangeLanguageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart:.
        /// </summary>
        internal static string ChartOptions {
            get {
                return ResourceManager.GetString("ChartOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Type:.
        /// </summary>
        internal static string ChartType {
            get {
                return ResourceManager.GetString("ChartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child saved successfully. Child ID:.
        /// </summary>
        internal static string ChildSaved {
            get {
                return ResourceManager.GetString("ChildSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circumference.
        /// </summary>
        internal static string Circumference {
            get {
                return ResourceManager.GetString("Circumference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this comment?.
        /// </summary>
        internal static string ConfirmCommentDelete {
            get {
                return ResourceManager.GetString("ConfirmCommentDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact saved successfully. Contact ID:.
        /// </summary>
        internal static string ContactSaved {
            get {
                return ResourceManager.GetString("ContactSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        internal static string Context {
            get {
                return ResourceManager.GetString("Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context:.
        /// </summary>
        internal static string ContextColon {
            get {
                return ResourceManager.GetString("ContextColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days old..
        /// </summary>
        internal static string DaysOld {
            get {
                return ResourceManager.GetString("DaysOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Access.
        /// </summary>
        internal static string DeleteAccess {
            get {
                return ResourceManager.GetString("DeleteAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove access for this user:.
        /// </summary>
        internal static string DeleteAccessMessage {
            get {
                return ResourceManager.GetString("DeleteAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Comment.
        /// </summary>
        internal static string DeleteCommentTitle {
            get {
                return ResourceManager.GetString("DeleteCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        internal static string DurationColon {
            get {
                return ResourceManager.GetString("DurationColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Add child failed. Try again later..
        /// </summary>
        internal static string ErrorChildNotSaved {
            get {
                return ResourceManager.GetString("ErrorChildNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Contact was not saved. Try again later..
        /// </summary>
        internal static string ErrorContactNotSaved {
            get {
                return ResourceManager.GetString("ErrorContactNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Friend was not saved. Try again later..
        /// </summary>
        internal static string ErrorFriendNotSaved {
            get {
                return ResourceManager.GetString("ErrorFriendNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Measurement not saved. Try againg later..
        /// </summary>
        internal static string ErrorMeasurementNotSaved {
            get {
                return ResourceManager.GetString("ErrorMeasurementNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Photo was not saved. Try again later..
        /// </summary>
        internal static string ErrorPhotoNotSaved {
            get {
                return ResourceManager.GetString("ErrorPhotoNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Skill was not saved. Try again later..
        /// </summary>
        internal static string ErrorSkillNotSaved {
            get {
                return ResourceManager.GetString("ErrorSkillNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Sleep was not saved. Try againg later..
        /// </summary>
        internal static string ErrorSleepNotSaved {
            get {
                return ResourceManager.GetString("ErrorSleepNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Adding user failed. Try again later..
        /// </summary>
        internal static string ErrorUserNotSaved {
            get {
                return ResourceManager.GetString("ErrorUserNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Color.
        /// </summary>
        internal static string EyeColor {
            get {
                return ResourceManager.GetString("EyeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string FamilyFriends {
            get {
                return ResourceManager.GetString("FamilyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Observation.
        /// </summary>
        internal static string FirstObservation {
            get {
                return ResourceManager.GetString("FirstObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        internal static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend saved successfully. Friend ID:.
        /// </summary>
        internal static string FriendSaved {
            get {
                return ResourceManager.GetString("FriendSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends since.
        /// </summary>
        internal static string FriendSince {
            get {
                return ResourceManager.GetString("FriendSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends Since:.
        /// </summary>
        internal static string FriendsSince {
            get {
                return ResourceManager.GetString("FriendsSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string FriendType {
            get {
                return ResourceManager.GetString("FriendType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of friend.
        /// </summary>
        internal static string FriendTypeLabel {
            get {
                return ResourceManager.GetString("FriendTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Color.
        /// </summary>
        internal static string HairColor {
            get {
                return ResourceManager.GetString("HairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours old..
        /// </summary>
        internal static string HoursOld {
            get {
                return ResourceManager.GetString("HoursOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is now.
        /// </summary>
        internal static string IsNow {
            get {
                return ResourceManager.GetString("IsNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Posts.
        /// </summary>
        internal static string LatestPosts {
            get {
                return ResourceManager.GetString("LatestPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string LocationColon {
            get {
                return ResourceManager.GetString("LocationColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in or register.
        /// </summary>
        internal static string LogInOrRegister {
            get {
                return ResourceManager.GetString("LogInOrRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements.
        /// </summary>
        internal static string Measurements {
            get {
                return ResourceManager.GetString("Measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement saved successfully. Measurement ID:.
        /// </summary>
        internal static string MeasurementSaved {
            get {
                return ResourceManager.GetString("MeasurementSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        internal static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes old..
        /// </summary>
        internal static string MinutesOld {
            get {
                return ResourceManager.GetString("MinutesOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        internal static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months old..
        /// </summary>
        internal static string MonthsOld {
            get {
                return ResourceManager.GetString("MonthsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Children.
        /// </summary>
        internal static string MyChildren {
            get {
                return ResourceManager.GetString("MyChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Family.
        /// </summary>
        internal static string MyFamily {
            get {
                return ResourceManager.GetString("MyFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer.
        /// </summary>
        internal static string Newer {
            get {
                return ResourceManager.GetString("Newer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have administrator rights for any children..
        /// </summary>
        internal static string NoChildrenFound {
            get {
                return ResourceManager.GetString("NoChildrenFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline: No internet connection..
        /// </summary>
        internal static string OfflineMessage {
            get {
                return ResourceManager.GetString("OfflineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older.
        /// </summary>
        internal static string Older {
            get {
                return ResourceManager.GetString("Older", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On  This Day.
        /// </summary>
        internal static string OnThisDay {
            get {
                return ResourceManager.GetString("OnThisDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page:.
        /// </summary>
        internal static string PageColon {
            get {
                return ResourceManager.GetString("PageColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents.
        /// </summary>
        internal static string ParentsFriends {
            get {
                return ResourceManager.GetString("ParentsFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Friends.
        /// </summary>
        internal static string PersonalFriends {
            get {
                return ResourceManager.GetString("PersonalFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Location:.
        /// </summary>
        internal static string PhotoLocation {
            get {
                return ResourceManager.GetString("PhotoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        internal static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo saved successfully. Photo ID:.
        /// </summary>
        internal static string PhotoSaved {
            get {
                return ResourceManager.GetString("PhotoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Taken:.
        /// </summary>
        internal static string PhotoTaken {
            get {
                return ResourceManager.GetString("PhotoTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture.
        /// </summary>
        internal static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Child.
        /// </summary>
        internal static string SelectChild {
            get {
                return ResourceManager.GetString("SelectChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        internal static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language/Sprache/Sprog.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show:.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Timeline before:.
        /// </summary>
        internal static string ShowTimelineBefore {
            get {
                return ResourceManager.GetString("ShowTimelineBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill title or name.
        /// </summary>
        internal static string SkillName {
            get {
                return ResourceManager.GetString("SkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill saved successfully. Skill ID:.
        /// </summary>
        internal static string SkillSaved {
            get {
                return ResourceManager.GetString("SkillSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        internal static string Sleep {
            get {
                return ResourceManager.GetString("Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep recorded in the last 30 days:.
        /// </summary>
        internal static string SleepRecordedInTheLast30Days {
            get {
                return ResourceManager.GetString("SleepRecordedInTheLast30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep recorded in the last year:.
        /// </summary>
        internal static string SleepRecordedInTheLastYear {
            get {
                return ResourceManager.GetString("SleepRecordedInTheLastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep saved successfully. Sleep ID:.
        /// </summary>
        internal static string SleepSaved {
            get {
                return ResourceManager.GetString("SleepSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By:.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Region.
        /// </summary>
        internal static string StateOrRegion {
            get {
                return ResourceManager.GetString("StateOrRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        internal static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        internal static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total sleep recorded:.
        /// </summary>
        internal static string TotalSleepRecorded {
            get {
                return ResourceManager.GetString("TotalSleepRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toys/Animals.
        /// </summary>
        internal static string ToyFriends {
            get {
                return ResourceManager.GetString("ToyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Events.
        /// </summary>
        internal static string UpcomingEvents {
            get {
                return ResourceManager.GetString("UpcomingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Access.
        /// </summary>
        internal static string UserAccess {
            get {
                return ResourceManager.GetString("UserAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User saved successfully. Access ID:.
        /// </summary>
        internal static string UserSaved {
            get {
                return ResourceManager.GetString("UserSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Location:.
        /// </summary>
        internal static string VideoLocation {
            get {
                return ResourceManager.GetString("VideoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Taken:.
        /// </summary>
        internal static string VideoTaken {
            get {
                return ResourceManager.GetString("VideoTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was.
        /// </summary>
        internal static string Was {
            get {
                return ResourceManager.GetString("Was", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        internal static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks and.
        /// </summary>
        internal static string WeeksAnd {
            get {
                return ResourceManager.GetString("WeeksAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will be.
        /// </summary>
        internal static string WillBe {
            get {
                return ResourceManager.GetString("WillBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years old..
        /// </summary>
        internal static string YearsOld {
            get {
                return ResourceManager.GetString("YearsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
