//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinaUnaXamarin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KinaUnaXamarin.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Info.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Level.
        /// </summary>
        internal static string AccessLevel {
            get {
                return ResourceManager.GetString("AccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Calendar Event.
        /// </summary>
        internal static string AddCalendarEvent {
            get {
                return ResourceManager.GetString("AddCalendarEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Calendar Event for:.
        /// </summary>
        internal static string AddCalendarEventFor {
            get {
                return ResourceManager.GetString("AddCalendarEventFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Child.
        /// </summary>
        internal static string AddChild {
            get {
                return ResourceManager.GetString("AddChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        internal static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contact.
        /// </summary>
        internal static string AddContact {
            get {
                return ResourceManager.GetString("AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contact for:.
        /// </summary>
        internal static string AddContactFor {
            get {
                return ResourceManager.GetString("AddContactFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Friend.
        /// </summary>
        internal static string AddFriend {
            get {
                return ResourceManager.GetString("AddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Friend for:.
        /// </summary>
        internal static string AddFriendFor {
            get {
                return ResourceManager.GetString("AddFriendFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        internal static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Location.
        /// </summary>
        internal static string AddLocation {
            get {
                return ResourceManager.GetString("AddLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Location for:.
        /// </summary>
        internal static string AddLocationFor {
            get {
                return ResourceManager.GetString("AddLocationFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Measurement.
        /// </summary>
        internal static string AddMeasurement {
            get {
                return ResourceManager.GetString("AddMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Measurement for:.
        /// </summary>
        internal static string AddMeasurementFor {
            get {
                return ResourceManager.GetString("AddMeasurementFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        internal static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note for:.
        /// </summary>
        internal static string AddNoteFor {
            get {
                return ResourceManager.GetString("AddNoteFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photo.
        /// </summary>
        internal static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photo for:.
        /// </summary>
        internal static string AddPhotoFor {
            get {
                return ResourceManager.GetString("AddPhotoFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        internal static string AddressLine1 {
            get {
                return ResourceManager.GetString("AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        internal static string AddressLine2 {
            get {
                return ResourceManager.GetString("AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Skill.
        /// </summary>
        internal static string AddSkill {
            get {
                return ResourceManager.GetString("AddSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Skill for:.
        /// </summary>
        internal static string AddSkillFor {
            get {
                return ResourceManager.GetString("AddSkillFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sleep.
        /// </summary>
        internal static string AddSleep {
            get {
                return ResourceManager.GetString("AddSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sleep for:.
        /// </summary>
        internal static string AddSleepFor {
            get {
                return ResourceManager.GetString("AddSleepFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User for:.
        /// </summary>
        internal static string AddUserFor {
            get {
                return ResourceManager.GetString("AddUserFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vaccination.
        /// </summary>
        internal static string AddVaccination {
            get {
                return ResourceManager.GetString("AddVaccination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vaccination for:.
        /// </summary>
        internal static string AddVaccinationFor {
            get {
                return ResourceManager.GetString("AddVaccinationFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Video.
        /// </summary>
        internal static string AddVideo {
            get {
                return ResourceManager.GetString("AddVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Video for:.
        /// </summary>
        internal static string AddVideoFor {
            get {
                return ResourceManager.GetString("AddVideoFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Word (Vocabulary).
        /// </summary>
        internal static string AddVocabulary {
            get {
                return ResourceManager.GetString("AddVocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Word for:.
        /// </summary>
        internal static string AddVocabularyFor {
            get {
                return ResourceManager.GetString("AddVocabularyFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrators.
        /// </summary>
        internal static string Administrators {
            get {
                return ResourceManager.GetString("Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Day.
        /// </summary>
        internal static string AllDay {
            get {
                return ResourceManager.GetString("AllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Tags.
        /// </summary>
        internal static string AllTags {
            get {
                return ResourceManager.GetString("AllTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        internal static string Altitude {
            get {
                return ResourceManager.GetString("Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average sleep per day:.
        /// </summary>
        internal static string AverageSleepPerDay {
            get {
                return ResourceManager.GetString("AverageSleepPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average sleep per day in the last 30 days:.
        /// </summary>
        internal static string AverageSleepPerDayInTheLast30Days {
            get {
                return ResourceManager.GetString("AverageSleepPerDayInTheLast30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average sleep per day in the last year:.
        /// </summary>
        internal static string AverageSleepPerDayInTheLastYear {
            get {
                return ResourceManager.GetString("AverageSleepPerDayInTheLastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        internal static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caretakers.
        /// </summary>
        internal static string CaretakerFriends {
            get {
                return ResourceManager.GetString("CaretakerFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: When changing language, some text may appear in the previously selected language until the app is restarted..
        /// </summary>
        internal static string ChangeLanguageWarning {
            get {
                return ResourceManager.GetString("ChangeLanguageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart:.
        /// </summary>
        internal static string ChartOptions {
            get {
                return ResourceManager.GetString("ChartOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Type:.
        /// </summary>
        internal static string ChartType {
            get {
                return ResourceManager.GetString("ChartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Child was successfully saved. Child ID:.
        /// </summary>
        internal static string ChildSaved {
            get {
                return ResourceManager.GetString("ChildSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circumference.
        /// </summary>
        internal static string Circumference {
            get {
                return ResourceManager.GetString("Circumference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this comment?.
        /// </summary>
        internal static string ConfirmCommentDelete {
            get {
                return ResourceManager.GetString("ConfirmCommentDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Contact was successfully saved. Contact ID:.
        /// </summary>
        internal static string ContactSaved {
            get {
                return ResourceManager.GetString("ContactSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        internal static string Context {
            get {
                return ResourceManager.GetString("Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context:.
        /// </summary>
        internal static string ContextColon {
            get {
                return ResourceManager.GetString("ContextColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        internal static string County {
            get {
                return ResourceManager.GetString("County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and Time.
        /// </summary>
        internal static string DateAndTime {
            get {
                return ResourceManager.GetString("DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days old..
        /// </summary>
        internal static string DaysOld {
            get {
                return ResourceManager.GetString("DaysOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Access.
        /// </summary>
        internal static string DeleteAccess {
            get {
                return ResourceManager.GetString("DeleteAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove access for this user:.
        /// </summary>
        internal static string DeleteAccessMessage {
            get {
                return ResourceManager.GetString("DeleteAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Comment.
        /// </summary>
        internal static string DeleteCommentTitle {
            get {
                return ResourceManager.GetString("DeleteCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Contact.
        /// </summary>
        internal static string DeleteContact {
            get {
                return ResourceManager.GetString("DeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this contact.
        /// </summary>
        internal static string DeleteContactMessage {
            get {
                return ResourceManager.GetString("DeleteContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Event.
        /// </summary>
        internal static string DeleteEvent {
            get {
                return ResourceManager.GetString("DeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this calendar event.
        /// </summary>
        internal static string DeleteEventMessage {
            get {
                return ResourceManager.GetString("DeleteEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Friend.
        /// </summary>
        internal static string DeleteFriend {
            get {
                return ResourceManager.GetString("DeleteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this friend.
        /// </summary>
        internal static string DeleteFriendMessage {
            get {
                return ResourceManager.GetString("DeleteFriendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Location.
        /// </summary>
        internal static string DeleteLocation {
            get {
                return ResourceManager.GetString("DeleteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this location.
        /// </summary>
        internal static string DeleteLocationMessage {
            get {
                return ResourceManager.GetString("DeleteLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Measurement.
        /// </summary>
        internal static string DeleteMeasurement {
            get {
                return ResourceManager.GetString("DeleteMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this measurement.
        /// </summary>
        internal static string DeleteMeasurementMessage {
            get {
                return ResourceManager.GetString("DeleteMeasurementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Note.
        /// </summary>
        internal static string DeleteNote {
            get {
                return ResourceManager.GetString("DeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this note.
        /// </summary>
        internal static string DeleteNoteMessage {
            get {
                return ResourceManager.GetString("DeleteNoteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Skill.
        /// </summary>
        internal static string DeleteSkill {
            get {
                return ResourceManager.GetString("DeleteSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this skill.
        /// </summary>
        internal static string DeleteSkillMessage {
            get {
                return ResourceManager.GetString("DeleteSkillMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Sleep.
        /// </summary>
        internal static string DeleteSleep {
            get {
                return ResourceManager.GetString("DeleteSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this sleep record.
        /// </summary>
        internal static string DeleteSleepMessage {
            get {
                return ResourceManager.GetString("DeleteSleepMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Vaccination.
        /// </summary>
        internal static string DeleteVaccination {
            get {
                return ResourceManager.GetString("DeleteVaccination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this vaccination.
        /// </summary>
        internal static string DeleteVaccinationMessage {
            get {
                return ResourceManager.GetString("DeleteVaccinationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Word.
        /// </summary>
        internal static string DeleteWord {
            get {
                return ResourceManager.GetString("DeleteWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this word.
        /// </summary>
        internal static string DeleteWordMessage {
            get {
                return ResourceManager.GetString("DeleteWordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        internal static string DurationColon {
            get {
                return ResourceManager.GetString("DurationColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 1.
        /// </summary>
        internal static string Email1 {
            get {
                return ResourceManager.GetString("Email1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 2.
        /// </summary>
        internal static string Email2 {
            get {
                return ResourceManager.GetString("Email2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Add child failed. Try again later..
        /// </summary>
        internal static string ErrorChildNotSaved {
            get {
                return ResourceManager.GetString("ErrorChildNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The Contact was not saved. Try again later..
        /// </summary>
        internal static string ErrorContactNotSaved {
            get {
                return ResourceManager.GetString("ErrorContactNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The Calendar Event was not saved. Try again later..
        /// </summary>
        internal static string ErrorEventNotSaved {
            get {
                return ResourceManager.GetString("ErrorEventNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The Friend was not saved. Try again later..
        /// </summary>
        internal static string ErrorFriendNotSaved {
            get {
                return ResourceManager.GetString("ErrorFriendNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The Location was not saved. Try again later..
        /// </summary>
        internal static string ErrorLocationNotSaved {
            get {
                return ResourceManager.GetString("ErrorLocationNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The Measurement not saved. Try againg later..
        /// </summary>
        internal static string ErrorMeasurementNotSaved {
            get {
                return ResourceManager.GetString("ErrorMeasurementNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The Note was not saved. Try again later..
        /// </summary>
        internal static string ErrorNoteNotSaved {
            get {
                return ResourceManager.GetString("ErrorNoteNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The Photo was not saved. Try again later..
        /// </summary>
        internal static string ErrorPhotoNotSaved {
            get {
                return ResourceManager.GetString("ErrorPhotoNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The Skill was not saved. Try again later..
        /// </summary>
        internal static string ErrorSkillNotSaved {
            get {
                return ResourceManager.GetString("ErrorSkillNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The Sleep was not saved. Try againg later..
        /// </summary>
        internal static string ErrorSleepNotSaved {
            get {
                return ResourceManager.GetString("ErrorSleepNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Adding user failed. Try again later..
        /// </summary>
        internal static string ErrorUserNotSaved {
            get {
                return ResourceManager.GetString("ErrorUserNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The Vaccination was not saved. Try again later..
        /// </summary>
        internal static string ErrorVaccinationNotSaved {
            get {
                return ResourceManager.GetString("ErrorVaccinationNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The Video was not saved. Try again later..
        /// </summary>
        internal static string ErrorVideoNotSaved {
            get {
                return ResourceManager.GetString("ErrorVideoNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The Word was not saved. Try again later..
        /// </summary>
        internal static string ErrorWordNotSaved {
            get {
                return ResourceManager.GetString("ErrorWordNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Calendar Event was successfully saved. Event ID:.
        /// </summary>
        internal static string EventSaved {
            get {
                return ResourceManager.GetString("EventSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Color.
        /// </summary>
        internal static string EyeColor {
            get {
                return ResourceManager.GetString("EyeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string FamilyFriends {
            get {
                return ResourceManager.GetString("FamilyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Observation.
        /// </summary>
        internal static string FirstObservation {
            get {
                return ResourceManager.GetString("FirstObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        internal static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Friend was successfully saved. Friend ID:.
        /// </summary>
        internal static string FriendSaved {
            get {
                return ResourceManager.GetString("FriendSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends since.
        /// </summary>
        internal static string FriendSince {
            get {
                return ResourceManager.GetString("FriendSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends Since:.
        /// </summary>
        internal static string FriendsSince {
            get {
                return ResourceManager.GetString("FriendsSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string FriendType {
            get {
                return ResourceManager.GetString("FriendType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of friend.
        /// </summary>
        internal static string FriendTypeLabel {
            get {
                return ResourceManager.GetString("FriendTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get my current location.
        /// </summary>
        internal static string GetLocation {
            get {
                return ResourceManager.GetString("GetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Color.
        /// </summary>
        internal static string HairColor {
            get {
                return ResourceManager.GetString("HairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours old..
        /// </summary>
        internal static string HoursOld {
            get {
                return ResourceManager.GetString("HoursOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Number.
        /// </summary>
        internal static string HouseNumber {
            get {
                return ResourceManager.GetString("HouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is now.
        /// </summary>
        internal static string IsNow {
            get {
                return ResourceManager.GetString("IsNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Posts.
        /// </summary>
        internal static string LatestPosts {
            get {
                return ResourceManager.GetString("LatestPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string LocationColon {
            get {
                return ResourceManager.GetString("LocationColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Location was successfully saved. Location ID:.
        /// </summary>
        internal static string LocationSaved {
            get {
                return ResourceManager.GetString("LocationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in or register.
        /// </summary>
        internal static string LogInOrRegister {
            get {
                return ResourceManager.GetString("LogInOrRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements.
        /// </summary>
        internal static string Measurements {
            get {
                return ResourceManager.GetString("Measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Measurement was successfully saved. Measurement ID:.
        /// </summary>
        internal static string MeasurementSaved {
            get {
                return ResourceManager.GetString("MeasurementSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        internal static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes old..
        /// </summary>
        internal static string MinutesOld {
            get {
                return ResourceManager.GetString("MinutesOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        internal static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months old..
        /// </summary>
        internal static string MonthsOld {
            get {
                return ResourceManager.GetString("MonthsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Children.
        /// </summary>
        internal static string MyChildren {
            get {
                return ResourceManager.GetString("MyChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Family.
        /// </summary>
        internal static string MyFamily {
            get {
                return ResourceManager.GetString("MyFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name or Label.
        /// </summary>
        internal static string NameOrLabel {
            get {
                return ResourceManager.GetString("NameOrLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer.
        /// </summary>
        internal static string Newer {
            get {
                return ResourceManager.GetString("Newer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have administrator rights for any children..
        /// </summary>
        internal static string NoChildrenFound {
            get {
                return ResourceManager.GetString("NoChildrenFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comments for this photo.
        /// </summary>
        internal static string NoCommentsToDisplay {
            get {
                return ResourceManager.GetString("NoCommentsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Note was successfully saved. Note ID:.
        /// </summary>
        internal static string NoteSaved {
            get {
                return ResourceManager.GetString("NoteSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline: No internet connection..
        /// </summary>
        internal static string OfflineMessage {
            get {
                return ResourceManager.GetString("OfflineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older.
        /// </summary>
        internal static string Older {
            get {
                return ResourceManager.GetString("Older", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On  This Day.
        /// </summary>
        internal static string OnThisDay {
            get {
                return ResourceManager.GetString("OnThisDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page:.
        /// </summary>
        internal static string PageColon {
            get {
                return ResourceManager.GetString("PageColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents.
        /// </summary>
        internal static string ParentsFriends {
            get {
                return ResourceManager.GetString("ParentsFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste the link or embed code here.
        /// </summary>
        internal static string PasteVideoLink {
            get {
                return ResourceManager.GetString("PasteVideoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Friends.
        /// </summary>
        internal static string PersonalFriends {
            get {
                return ResourceManager.GetString("PersonalFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Location:.
        /// </summary>
        internal static string PhotoLocation {
            get {
                return ResourceManager.GetString("PhotoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Locations.
        /// </summary>
        internal static string PhotoLocations {
            get {
                return ResourceManager.GetString("PhotoLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        internal static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Photo was successfully saved. Photo ID:.
        /// </summary>
        internal static string PhotoSaved {
            get {
                return ResourceManager.GetString("PhotoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Taken:.
        /// </summary>
        internal static string PhotoTaken {
            get {
                return ResourceManager.GetString("PhotoTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture.
        /// </summary>
        internal static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Child.
        /// </summary>
        internal static string SelectChild {
            get {
                return ResourceManager.GetString("SelectChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        internal static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language/Sprache/Sprog.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show:.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only active contacts.
        /// </summary>
        internal static string ShowOnlyActive {
            get {
                return ResourceManager.GetString("ShowOnlyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Timeline before:.
        /// </summary>
        internal static string ShowTimelineBefore {
            get {
                return ResourceManager.GetString("ShowTimelineBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill title or name.
        /// </summary>
        internal static string SkillName {
            get {
                return ResourceManager.GetString("SkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Skill was successfully saved. Skill ID:.
        /// </summary>
        internal static string SkillSaved {
            get {
                return ResourceManager.GetString("SkillSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        internal static string Sleep {
            get {
                return ResourceManager.GetString("Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep recorded in the last 30 days:.
        /// </summary>
        internal static string SleepRecordedInTheLast30Days {
            get {
                return ResourceManager.GetString("SleepRecordedInTheLast30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep recorded in the last year:.
        /// </summary>
        internal static string SleepRecordedInTheLastYear {
            get {
                return ResourceManager.GetString("SleepRecordedInTheLastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sleep was successfully saved. Sleep ID:.
        /// </summary>
        internal static string SleepSaved {
            get {
                return ResourceManager.GetString("SleepSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By:.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds Like.
        /// </summary>
        internal static string SoundsLike {
            get {
                return ResourceManager.GetString("SoundsLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Region.
        /// </summary>
        internal static string StateOrRegion {
            get {
                return ResourceManager.GetString("StateOrRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        internal static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        internal static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total sleep recorded:.
        /// </summary>
        internal static string TotalSleepRecorded {
            get {
                return ResourceManager.GetString("TotalSleepRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toys/Animals.
        /// </summary>
        internal static string ToyFriends {
            get {
                return ResourceManager.GetString("ToyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Events.
        /// </summary>
        internal static string UpcomingEvents {
            get {
                return ResourceManager.GetString("UpcomingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Access.
        /// </summary>
        internal static string UserAccess {
            get {
                return ResourceManager.GetString("UserAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Access was successfully saved. Access ID:.
        /// </summary>
        internal static string UserSaved {
            get {
                return ResourceManager.GetString("UserSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaccination Name.
        /// </summary>
        internal static string VaccinationName {
            get {
                return ResourceManager.GetString("VaccinationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaccinations.
        /// </summary>
        internal static string Vaccinations {
            get {
                return ResourceManager.GetString("Vaccinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Vaccination was successfully saved. Vaccination ID:.
        /// </summary>
        internal static string VaccinationSaved {
            get {
                return ResourceManager.GetString("VaccinationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Location:.
        /// </summary>
        internal static string VideoLocation {
            get {
                return ResourceManager.GetString("VideoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Video was successfully saved. Video ID:.
        /// </summary>
        internal static string VideoSaved {
            get {
                return ResourceManager.GetString("VideoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Taken:.
        /// </summary>
        internal static string VideoTaken {
            get {
                return ResourceManager.GetString("VideoTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocabulary.
        /// </summary>
        internal static string Vocabulary {
            get {
                return ResourceManager.GetString("Vocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was.
        /// </summary>
        internal static string Was {
            get {
                return ResourceManager.GetString("Was", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        internal static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks and.
        /// </summary>
        internal static string WeeksAnd {
            get {
                return ResourceManager.GetString("WeeksAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will be.
        /// </summary>
        internal static string WillBe {
            get {
                return ResourceManager.GetString("WillBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        internal static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Word was successfully saved. Word ID:.
        /// </summary>
        internal static string WordSaved {
            get {
                return ResourceManager.GetString("WordSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years old..
        /// </summary>
        internal static string YearsOld {
            get {
                return ResourceManager.GetString("YearsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
